/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cn.spider.app;

public class App {
//    public static void main(String[] args) {
//        LinkedList tokens;
//        tokens = split(getMessage());
//        String result = join(tokens);
//        System.out.println(WordUtils.capitalize(result));
//        Locale defaultLocale = Locale.getDefault();
//        System.out.println(defaultLocale.getDisplayName());
//        Locale[] availableLocales = Locale.getAvailableLocales();
//        Arrays.stream(availableLocales).forEach(a-> System.out.println(a.getDisplayName()));
//        Locale.setDefault(Locale.forLanguageTag("el"));
//
//    }
}
